topic: ecommerce_browsing_cart
context:
  description: Simulated e-commerce browsing and cart activity data for personalization, conversion, and abandonment analytics.
  industries: [E-commerce, Retail, Online Marketplace]
  notes: |
    - Includes user, session, product, cart, and abandonment fields.
    - Useful for recommendation engines, recovery campaigns, and sales forecasting.
fields:
  - name: session_id
    type: int
    min: 1000000
    max: 9999999
  - name: user_id
    type: int
    min: 10000
    max: 99999
  - name: user_first_name
    type: choice
    values: ["Alex", "Jordan", "Morgan", "Taylor", "Casey", "Riley", "Jamie", "Avery", "Peyton", "Quinn"]
  - name: user_last_name
    type: choice
    values: ["Kim", "Smith", "Lee", "Patel", "Brown", "Garcia", "Davis", "Martinez", "Wilson", "Chen"]
  - name: product_id
    type: int
    min: 1000
    max: 9999
  - name: product_name
    type: choice
    values: ["Sneakers", "Backpack", "Smartphone", "Headphones", "Coffee Maker", "T-shirt", "Watch", "Sunglasses", "Book", "Tablet"]
  - name: action
    type: choice
    values: [View, Add to Cart, Remove from Cart, Purchase, Abandon Cart]
  - name: price
    type: float
    min: 5.0
    max: 2000.0
  - name: quantity
    type: int
    min: 1
    max: 5
  - name: cart_value
    type: formula
    formula: price * quantity
  - name: abandoned
    type: choice
    values: [false, false, false, true]  # ~25% abandoned
  - name: timestamp
    type: date
    start: 2024-01-01
    end: 2025-01-01
    time_format: '%Y-%m-%dT%H:%M:%S'
