topic: hr_workforce
context:
  description: Simulated HR and workforce data for employee analytics, payroll, and performance management.
  industries: [HR, Enterprise, Staffing, Payroll]
  notes: |
    - Includes employee, department, salary, hire/termination dates, and performance fields.
    - Useful for workforce planning, attrition analysis, and HR analytics demos.
fields:
  - name: employee_id
    type: int
    min: 10000
    max: 99999
  - name: first_name
    type: faker
    faker_method: first_name
  - name: last_name
    type: faker
    faker_method: last_name
  - name: employer
    type: faker
    faker_method: company
  - name: department
    type: choice
    values: [Engineering, Sales, Marketing, HR, Finance, Operations, Support, Product, IT, Legal]
  - name: job_title
    type: choice
    values: [Engineer, Manager, Analyst, Director, Specialist, Coordinator, Executive]
  - name: job_level
    type: choice
    values: [Entry, Associate, Senior, Lead, Manager, Director, VP, C-Level]
  - name: salary
    type: float
    min: 40000.0
    max: 250000.0
  - name: hire_date
    type: date
    start: 2015-01-01
    end: 2024-01-01
  - name: termination_date
    type: date
    start: 2015-01-01
    end: 2024-12-31
  - name: tenure_years
    type: float
    min: 0.0
    max: 40.0
  - name: attrition_risk
    type: choice
    values: [Low, Medium, High]
    weights: [0.7, 0.2, 0.1]
  - name: engagement_score
    type: float
    min: 0.0
    max: 1.0
  - name: gender
    type: choice
    values: [Male, Female, Other]
  - name: ethnicity
    type: choice
    values: [White, Black, Asian, Hispanic, Native American, Pacific Islander, Other]
