topic: real_estate
context:
  description: Simulated real estate property listings and transaction data for analytics, search, and recommendation use cases.
  industries: [Real Estate, PropTech, Finance, Insurance]
  notes: |
    - Includes property, agent, listing, and transaction fields.
    - Useful for property search, price prediction, and market analysis.
fields:
  - name: property_id
    type: int
    min: 100000
    max: 999999
  - name: address
    type: faker
    faker_method: address
  - name: synthetic_address
    type: string
    pattern: '{int},{street},{city},{state} {zip}'
    components:
      int:
        type: int
        min: 100
        max: 9999
      street:
        type: choice
        values: ["Main St", "Oak Ave", "Pine Rd", "Maple Dr", "Cedar Ln", "Elm St", "Sunset Blvd", "Park Ave", "Lakeview Ct", "Hilltop Rd"]
      city:
        type: choice
        values: ["Springfield", "Riverton", "Lakeside", "Fairview", "Greenville", "Franklin", "Madison", "Georgetown", "Clinton", "Ashland"]
      state:
        type: choice
        values: [CA, TX, NY, FL, IL, WA, CO, MA, GA, NC]
      zip:
        type: int
        min: 10000
        max: 99999
  - name: property_type
    type: choice
    values: [Single Family, Condo, Townhouse, Apartment, Multi-Family, Land, Commercial]
  - name: bedrooms
    type: int
    min: 1
    max: 7
  - name: bathrooms
    type: float
    min: 1.0
    max: 5.0
  - name: square_feet
    type: int
    min: 400
    max: 8000
  - name: year_built
    type: int
    min: 1900
    max: 2024
  - name: listing_price
    type: int
    min: 50000
    max: 5000000
  - name: status
    type: choice
    values: [Active, Pending, Sold, Off Market]
    weights: [0.5, 0.2, 0.25, 0.05]
  - name: agent_name
    type: faker
    faker_method: name
  - name: listing_date
    type: date
    start: 2024-01-01
    end: 2025-01-01
    time_format: '%Y-%m-%d'
  - name: sale_date
    type: date
    start: 2024-01-01
    end: 2025-08-15
    time_format: '%Y-%m-%d'
  - name: sale_price
    type: formula
    formula: 'listing_price if status != "Sold" else int(listing_price * random.uniform(0.95, 1.05))'
  - name: features
    type: multi_choice
    values: [Garage, Pool, Fireplace, Basement, Garden, Solar Panels, Smart Home, Walk-In Closet, Deck, Fenced Yard]
    min_choices: 0
    max_choices: 5
